GRANT SELECT ON USUARIOS TO US_BDOBJECTUAL;
GRANT SELECT ON HORAS TO US_BDOBJECTUAL;
GRANT SELECT ON NOTAS TO US_BDOBJECTUAL;
GRANT SELECT ON ESTADOS_EXAMENES TO US_BDOBJECTUAL;
GRANT INSERT ON EXAMENES_ORALES_PRESENTADOS TO US_BDOBJECTUAL;
GRANT INSERT ON EXAMENES_ESCRITOS_PRESENTADOS TO US_BDOBJECTUAL;